
version: '3.8'
services:
  app:
    build: ./
    image: andrewodrain/web-applications-app:v0.0.1
    container_name: portfolio-web-app

  nginx:
    build: ./nginx
    image: andrewodrain/web-applications-nginx:v0.1
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app

