services:

  psql:
    build: ./database
    image: andrewodrain/web-applications:psql-v0.0.2
    container_name: psql_container
    env_file:
      - ./database/psql_container.env

  app:
    build: ./
    image: andrewodrain/web-applications:app-v0.0.2
    container_name: app_container
    env_file:
      - ./app_container.env
    depends_on:
      - psql
      - redis

  redis:
    build: ./redis
    image: andrewodrain/web-applications:redis-v0.0.2
    container_name: redis_container
    env_file:
      - ./redis/redis_container.env

  nginx:
    build: ./nginx
    image: andrewodrain/web-applications:nginx-v0.0.2
    container_name: nginx_container
    env_file:
      - ./nginx/nginx_container.env
    ports:
      - "80:80"
    depends_on:
      - app

