version: '3.8'

services:

  psql:
    build: ./database
    image: andrewodrain/web-applications:psql-v0.0.2
    container_name: psql_container
    env_file:
      - ./database/psql_container.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/postgresql.conf:/etc/postgresql/16/main/postgresql.conf:ro
      - ./database/logs:/var/log/postgresql
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build: ./
    image: andrewodrain/web-applications:app-v0.0.2
    container_name: app_container
    env_file:
      - app_container.env
    ports:
      - "5000:5000"
    volumes:
      - ./logs/flask:/app/logs/flask
      - ./logs/gunicorn:/app/logs/gunicorn
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - psql

  nginx:
    build: ./nginx
    image: andrewodrain/web-applications:nginx-v0.0.2
    container_name: nginx_container
    env_file:
      - ./nginx/nginx_container.env
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx:ro
      - ./nginx/nginx_logs:/var/log/nginx
      - ./nginx/modsecurity/conf:/etc/modsecurity:ro
      - ./nginx/modsecurity/logs:/var/log/modsecurity
      - ./nginx/modsecurity/data:/var/modsecurity/data
      - ./nginx/modsecurity/tmp:/var/modsecurity/tmp
      - ./nginx/modsecurity/debug_logs:/opt/modsecurity/var/log
      - ./nginx/healthd_logs:/var/log/nginx/healthd
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - app

volumes:
  db-data: { }
